config/routes.rb
Rails.application.routes.draw do

  get 'restaurants/random', to: 'restaurants#random'
  post 'restaurants/random', to: 'restaurants#random'
  get 'activities/random', to: 'activities#random'
  post 'activities/random', to: 'activities#random'
  resources :restaurants
  resources :activities
  resources :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :restaurants
  has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :select_activity, only: [:show, :edit, :update, :destroy]

  def index
    @activities = Activity.all
  end

  def random
    @activities = Activity.all
    redirect_to get_random_activity
  end

  def show
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.create(activities_params)
    redirect_to activities_path
  end

  def edit
  end

  def update
    @activity.update(activities_params)
    redirect_to activities_path
  end

  def destroy
    @activity.destroy
    redirect_to activities_path
  end

  def select_activity
    @activity = Activity.find(params[:id])
  end

  private
  def activities_params
    params.require(:activity).permit(:description, :user_id)
  end

  def get_random_activity
    activity = Activity.all.sample(1)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :select_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end

  def random
    @restaurants = Restaurant.all
    redirect_to get_random_restaurant
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    redirect_to restaurants_path
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  def select_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def get_random_restaurant
      restaurant = Restaurant.all.sample(1)
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name,:url,:user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def edit
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/edit.html.erb
<h1>Edit Activity</h1>
<%= form_with model: @activity do |form| %>
  <%= form.text_field :description %><br>
  <br><br>
  <%= form.submit %>
<% end %>
<br><br>
<%= button_to "Delete Activity", @activity, :confirm => "Are you sure?", :method => :delete %>

app/views/activities/index.html.erb
<h1>My Activities</h1>
<%= button_to("Add Activity", 'activities/new', method:"get", class:"button_style" )%>
<br>
<%= button_to("Home Page", users_path, method:"get", class:"button_style" )%>
<br>
<ol>
  <% @activities.each do |activity|%>
    <li><%= link_to activity.description, edit_activity_path(activity) %></li>
  <%end%>
</ol>

app/views/activities/new.html.erb
<h1>Add an Activity</h1>
<%= form_with model: Activity.new do |form| %>
  <%= form.text_field :description, placeholder: "Activity Description" %><br>
  <%= form.text_field :user_id, placeholder: "User ID" %><br>
  <br><br>
  <%= form.submit %>
<% end %>

app/views/activities/show.html.erb
<h1>Try doing this:</h1>
<h2><%= @activity.description %></h2>

<img src="https://pbs.twimg.com/profile_images/378800000099889392/c47f40d0fb1549ed31443ebef54f31e8_400x400.png" height="200" width="200"></img>
<br>
<br>
<br>
<%= button_to "Next Activity", activities_random_path, method:"get", class:"next_activity_button"%>
<br>
<br>
<br>
<br>
<br>
<%= button_to("Home Page", users_path, method:"get", class:"button_style" )%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RandoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--  javascript_include_tag 'application', 'data-turbolinks-track': 'reload' -->
    <!-- makes it work with the iPhone -->
    <meta name="viewport" content ="width=device-width,initial-scale=1,user-scalable=yes" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>
<%= form_with model: @restaurant do |form| %>
  <%= form.text_field :name %><br>
  <%= form.text_field :url %><br>
  <br><br>
  <%= form.submit %>
<% end %>
<br><br>
<%= button_to "Delete Restaurant", @restaurant, :confirm => "Are you sure?", :method => :delete %>

app/views/restaurants/index.html.erb
<h1>My Restaurants</h1>
<br>
<%= button_to("Add Restaurant", 'restaurants/new', method:"get", class:"button_style" ) %>
<br>
<%= button_to("Home Page", users_path, method:"get", class:"button_style" )%>
<br>
<ol>
  <% @restaurants.each do |restaurant|%>
    <li><%= link_to restaurant.name, edit_restaurant_path(restaurant) %></li>
  <%end%>
</ol>

app/views/restaurants/new.html.erb
<h1>Add a Restaurant</h1>
<%= form_with model: Restaurant.new do |form| %>
  <%= form.text_field :name, placeholder: "Restaurant Name" %><br>
  <%= form.text_field :url, placeholder: "Google Maps URL" %><br>
  <%= form.text_field :user_id, placeholder: "User ID" %><br>
  <br><br>
  <%= form.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1>Try eating here:</h1>
<h2><%= link_to @restaurant.name, @restaurant.url %></h2>

<img src="https://pbs.twimg.com/profile_images/378800000099889392/c47f40d0fb1549ed31443ebef54f31e8_400x400.png" height="200" width="200"></img>
<br>
<br>
<br>
<%=button_to "Next Restaurant",restaurants_random_path, method:"get", class:"next_restaurant_button"%>
<br>
<br>
<br>
<br>
<br>
<%= button_to("Home Page", users_path, method:"get", class:"button_style") %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Hi Michael!</h1>
<h3>I'm Rando. I'm here to help!</h3>
<img src="https://pbs.twimg.com/profile_images/378800000099889392/c47f40d0fb1549ed31443ebef54f31e8_400x400.png" title= "Bark, bark!" height="200" width="200"></img>
<br>
<p>How are you?</p>
<br>
<div id='container1'>
  <%=button_to "I'm hungry", restaurants_random_path, mthod:"get", class:"choice_button" %>
  <br>
  <%=button_to "I'm bored", activities_random_path, method:"get", class:"choice_button" %>
</div>
<br>
<br>
<br>
<br>
<div id='container2'>
  <%=button_to('Change My Restaurants', restaurants_path, method:"get", class:"change_restaurant_button") %>
    <br>
  <%=button_to 'Change My Activities', activities_path, method:"get", class:"change_activity_button" %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>